---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        # - is a YAML indicator for a sequence item
        - image: dvdlaan/testrepo:backend
          name: backend
          imagePullPolicy: "Always"
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: backend